apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  annotations:
    argocd.argoproj.io/tracking-id: tasks-helm:apps/Deployment:{{ .Values.namespace }}/{{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    app_type: {{  .Values.app_type  }}
    service_type: {{  .Values.service_type  }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        app_type: {{  .Values.app_type  }}
        service_type: {{  .Values.service_type  }}
    spec:
      serviceAccount: {{ .Values.serviceAccount.name  }}
      serviceAccountName: {{ .Values.serviceAccount.name  }}
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
