apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app_type: {{ .Values.app_type }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: {{ .Values.name }}
