apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}
  labels:
    app_type: {{ .Values.app_type }}
    service_type: {{ .Values.service_type }} 
spec:
  type: NodePort
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.targetport }}
      nodePort: {{ .Values.nodeport }}
  selector:
    app: {{ .Values.name }}
