apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasks-helm
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: hevdin/flask-test
    argocd-image-updater.argoproj.io/hevdin.flask-test.update-strategy: newest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/hevdin.flask-test.force-update: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/Hevdin-twl/tasks.git
    targetRevision: main
    path: helm/flask_app
    helm:
      parameters:
        - name: image.repository
          value: hevdin/flask-test
        - name: image.tag
          value: 53f2b02
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

